imports:
    - { resource: ../src/TimeTracker/Resources/config/services.yaml }

# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

# https://symfony.com/doc/current/service_container.html#creating-configuring-services-in-the-container
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
